apiVersion: v1
appVersion: latest
home: https://get.twingate.com
description: Twingate Connector helm chart
name: connector
version: 0.1.1
maintainers: 
  - name: Roman Kournjaev
    email: roman@twingate.com