apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cn.fullname" . }}-config
type: Opaque
stringData:
  "connector.json": |-
    {
      "controller": {
        "mode": "access",
        "url": "https://{{ required "network Name required" .Values.connector.network }}.{{ .Values.connector.url }}",
        "token": {
          "data": {
            "access_token": "{{ required "Access Token required" .Values.connector.accessToken }}",
            "refresh_token": "{{ required "Refresh Token required" .Values.connector.refreshToken }}"
          }
        }
      }
      {{- if .Values.connector.dnsServer }}
      ,"afvpn": {
        "dns": "{{ .Values.connector.dnsServer }}"
      }
      {{- end }}
    }