{{- if not .Values.connector.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cn.fullname" . }}
  labels:
{{ include "cn.labels" . | indent 4 }}
{{- if .Values.additionalLabels -}}
  {{- toYaml .Values.additionalLabels | nindent 4 }}
{{- end }}
type: Opaque
data:
  TWINGATE_ACCESS_TOKEN: "{{ required "Access Token required" .Values.connector.accessToken | b64enc }}"
  TWINGATE_REFRESH_TOKEN: "{{ required "Refresh Token required" .Values.connector.refreshToken | b64enc }}"
{{- end -}}
