apiVersion: v1
kind: Secret
metadata:
  name: {{ include "an.fullname" . }}-config
type: Opaque
stringData:
  "access_node.json": |-
    {
      "controller": {
        "mode": "access",
        "url": "{{ .Values.accessNode.tenantUrl }}",
        "token": {
          "data": {
            "access_token": "{{ .Values.accessNode.accessToken }}",
            "refresh_token": "{{ .Values.accessNode.refreshToken }}"
          }
        }
      }
    }