apiVersion: v1
kind: Secret
metadata:
  name: {{ include "an.fullname" . }}-config
type: Opaque
stringData:
  "access_node.json": |-
    {
      "controller": {
        "mode": "access",
        "url": "https://{{ .Values.accessNode.tenant }}.{{ .Values.accessNode.url }}",
        "token": {
          "data": {
            "access_token": "{{ .Values.accessNode.accessToken }}",
            "refresh_token": "{{ .Values.accessNode.refreshToken }}"
          }
        }
      }
      {{- if .Values.accessNode.dnsServer }}
        ,"afvpn": {
          "dns": "{{ .Values.accessNode.dnsServer }}"
        }
      {{- end }}
    }